[build]
  command = "cd oncokidscare && composer install --no-dev --optimize-autoloader && npm install && npm run build"
  publish = "oncokidscare/public"

[[redirects]]
from = "/*"
to = "/index.php"
status = 200

[context.production.environment]
  APP_ENV = "prod"
  APP_DEBUG = "0"