<?php

namespace ContainerW2jIWsu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ya0Fm6MService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ya0Fm6M' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ya0Fm6M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'flasher' => ['services', 'flasher', 'getFlasherService', false],
        ], [
            'flasher' => '?',
        ]);
    }
}
