<?php

namespace ContainerW2jIWsu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5AHGnNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5AHGn_n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5AHGn_n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'flasher' => ['services', 'flasher', 'getFlasherService', false],
            'rapport' => ['privates', '.errored..service_locator.5AHGn_n.App\\Entity\\RapportDetat', NULL, 'Cannot autowire service ".service_locator.5AHGn_n": it needs an instance of "App\\Entity\\RapportDetat" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'flasher' => '?',
            'rapport' => 'App\\Entity\\RapportDetat',
        ]);
    }
}
