<?php

namespace ContainerW2jIWsu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9MWgsgwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9MWgsgw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9MWgsgw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rapportRepo' => ['privates', 'App\\Repository\\RapportDetatRepository', 'getRapportDetatRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'rapportRepo' => 'App\\Repository\\RapportDetatRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
