<?php

namespace ContainerW2jIWsu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRapportDetatService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5AHGn_n.App\Entity\RapportDetat' shared service.
     *
     * @return \App\Entity\RapportDetat
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5AHGn_n": it needs an instance of "App\\Entity\\RapportDetat" but this type has been excluded in "config/services.yaml".');
    }
}
