<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxn5lKU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxn5lKU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSxn5lKU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSxn5lKU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSxn5lKU\App_KernelDevDebugContainer([
    'container.build_hash' => 'Sxn5lKU',
    'container.build_id' => 'b7315856',
    'container.build_time' => 1739736904,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxn5lKU');
