<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMcUMktX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMcUMktX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMcUMktX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMcUMktX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMcUMktX\App_KernelDevDebugContainer([
    'container.build_hash' => 'McUMktX',
    'container.build_id' => '1074f9d6',
    'container.build_time' => 1739043927,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMcUMktX');
