<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOic1DFl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOic1DFl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOic1DFl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOic1DFl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOic1DFl\App_KernelDevDebugContainer([
    'container.build_hash' => 'Oic1DFl',
    'container.build_id' => '9647a962',
    'container.build_time' => 1739875308,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOic1DFl');
