controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
<<<<<<< HEAD

chatbot_test:
    path: /chatbot/test
    controller: App\Controller\ChatbotController::test
    methods: [GET]

chatbot_message:
    path: /chatbot/message
    controller: App\Controller\ChatbotController::message
    methods: [POST]
=======
>>>>>>> 0ed33a6b (KacemSuivi)
