parameters:
    images_directory: '%kernel.project_dir%/public/images'
    stripe.public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe.secret_key: '%env(STRIPE_SECRET_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

