services:
  mercure:
    image: dunglas/mercure:v0.15
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_EXTRA_DIRECTIVES: |
        anonymous
        cors_origins "http://127.0.0.1:8000" "https://127.0.0.1:8000"
    ports:
      - "3000:80"
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/.well-known/mercure"]
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mercure_data:
  mercure_config: