<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF2ck4Ep\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF2ck4Ep/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF2ck4Ep.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF2ck4Ep\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF2ck4Ep\App_KernelDevDebugContainer([
    'container.build_hash' => 'F2ck4Ep',
    'container.build_id' => '5a054eb3',
    'container.build_time' => 1739629866,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF2ck4Ep');
