<?php

namespace ContainerR4PBqlG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1BDjvx9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1BDjvx9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1BDjvx9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'likeRepository' => ['privates', 'App\\Repository\\LikeRepository', 'getLikeRepositoryService', true],
            'publication' => ['privates', '.errored..service_locator.1BDjvx9.App\\Entity\\Publication', NULL, 'Cannot autowire service ".service_locator.1BDjvx9": it needs an instance of "App\\Entity\\Publication" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'likeRepository' => 'App\\Repository\\LikeRepository',
            'publication' => 'App\\Entity\\Publication',
        ]);
    }
}
