<?php

namespace ContainerR4PBqlG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CdGrjpjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CdGrjpj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CdGrjpj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdminController::index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\AdminController::managePublications' => ['privates', '.service_locator.dH_7bkl', 'get_ServiceLocator_DH7bklService', true],
            'App\\Controller\\CommentController::delete' => ['privates', '.service_locator.sE8VhYE', 'get_ServiceLocator_SE8VhYEService', true],
            'App\\Controller\\CommentController::edit' => ['privates', '.service_locator.Xz_hH6b', 'get_ServiceLocator_XzHH6bService', true],
            'App\\Controller\\CommentController::index' => ['privates', '.service_locator.C15PbZX', 'get_ServiceLocator_C15PbZXService', true],
            'App\\Controller\\CommentController::new' => ['privates', '.service_locator.C15PbZX', 'get_ServiceLocator_C15PbZXService', true],
            'App\\Controller\\CommentController::show' => ['privates', '.service_locator.hAGYStx', 'get_ServiceLocator_HAGYStxService', true],
            'App\\Controller\\LikeController::likeComment' => ['privates', '.service_locator.sE8VhYE', 'get_ServiceLocator_SE8VhYEService', true],
            'App\\Controller\\LikeController::likePublication' => ['privates', '.service_locator.TyGfL3f', 'get_ServiceLocator_TyGfL3fService', true],
            'App\\Controller\\PublicationController::approve' => ['privates', '.service_locator.TyGfL3f', 'get_ServiceLocator_TyGfL3fService', true],
            'App\\Controller\\PublicationController::delete' => ['privates', '.service_locator.BXW8zd5', 'get_ServiceLocator_BXW8zd5Service', true],
            'App\\Controller\\PublicationController::edit' => ['privates', '.service_locator.md.U7iW', 'get_ServiceLocator_Md_U7iWService', true],
            'App\\Controller\\PublicationController::index' => ['privates', '.service_locator.dH_7bkl', 'get_ServiceLocator_DH7bklService', true],
            'App\\Controller\\PublicationController::like' => ['privates', '.service_locator.1BDjvx9', 'get_ServiceLocator_1BDjvx9Service', true],
            'App\\Controller\\PublicationController::new' => ['privates', '.service_locator.dH_7bkl', 'get_ServiceLocator_DH7bklService', true],
            'App\\Controller\\PublicationController::reject' => ['privates', '.service_locator.TyGfL3f', 'get_ServiceLocator_TyGfL3fService', true],
            'App\\Controller\\PublicationController::show' => ['privates', '.service_locator.iUig0G9', 'get_ServiceLocator_IUig0G9Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminController:index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\AdminController:managePublications' => ['privates', '.service_locator.dH_7bkl', 'get_ServiceLocator_DH7bklService', true],
            'App\\Controller\\CommentController:delete' => ['privates', '.service_locator.sE8VhYE', 'get_ServiceLocator_SE8VhYEService', true],
            'App\\Controller\\CommentController:edit' => ['privates', '.service_locator.Xz_hH6b', 'get_ServiceLocator_XzHH6bService', true],
            'App\\Controller\\CommentController:index' => ['privates', '.service_locator.C15PbZX', 'get_ServiceLocator_C15PbZXService', true],
            'App\\Controller\\CommentController:new' => ['privates', '.service_locator.C15PbZX', 'get_ServiceLocator_C15PbZXService', true],
            'App\\Controller\\CommentController:show' => ['privates', '.service_locator.hAGYStx', 'get_ServiceLocator_HAGYStxService', true],
            'App\\Controller\\LikeController:likeComment' => ['privates', '.service_locator.sE8VhYE', 'get_ServiceLocator_SE8VhYEService', true],
            'App\\Controller\\LikeController:likePublication' => ['privates', '.service_locator.TyGfL3f', 'get_ServiceLocator_TyGfL3fService', true],
            'App\\Controller\\PublicationController:approve' => ['privates', '.service_locator.TyGfL3f', 'get_ServiceLocator_TyGfL3fService', true],
            'App\\Controller\\PublicationController:delete' => ['privates', '.service_locator.BXW8zd5', 'get_ServiceLocator_BXW8zd5Service', true],
            'App\\Controller\\PublicationController:edit' => ['privates', '.service_locator.md.U7iW', 'get_ServiceLocator_Md_U7iWService', true],
            'App\\Controller\\PublicationController:index' => ['privates', '.service_locator.dH_7bkl', 'get_ServiceLocator_DH7bklService', true],
            'App\\Controller\\PublicationController:like' => ['privates', '.service_locator.1BDjvx9', 'get_ServiceLocator_1BDjvx9Service', true],
            'App\\Controller\\PublicationController:new' => ['privates', '.service_locator.dH_7bkl', 'get_ServiceLocator_DH7bklService', true],
            'App\\Controller\\PublicationController:reject' => ['privates', '.service_locator.TyGfL3f', 'get_ServiceLocator_TyGfL3fService', true],
            'App\\Controller\\PublicationController:show' => ['privates', '.service_locator.iUig0G9', 'get_ServiceLocator_IUig0G9Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminController::index' => '?',
            'App\\Controller\\AdminController::managePublications' => '?',
            'App\\Controller\\CommentController::delete' => '?',
            'App\\Controller\\CommentController::edit' => '?',
            'App\\Controller\\CommentController::index' => '?',
            'App\\Controller\\CommentController::new' => '?',
            'App\\Controller\\CommentController::show' => '?',
            'App\\Controller\\LikeController::likeComment' => '?',
            'App\\Controller\\LikeController::likePublication' => '?',
            'App\\Controller\\PublicationController::approve' => '?',
            'App\\Controller\\PublicationController::delete' => '?',
            'App\\Controller\\PublicationController::edit' => '?',
            'App\\Controller\\PublicationController::index' => '?',
            'App\\Controller\\PublicationController::like' => '?',
            'App\\Controller\\PublicationController::new' => '?',
            'App\\Controller\\PublicationController::reject' => '?',
            'App\\Controller\\PublicationController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:index' => '?',
            'App\\Controller\\AdminController:managePublications' => '?',
            'App\\Controller\\CommentController:delete' => '?',
            'App\\Controller\\CommentController:edit' => '?',
            'App\\Controller\\CommentController:index' => '?',
            'App\\Controller\\CommentController:new' => '?',
            'App\\Controller\\CommentController:show' => '?',
            'App\\Controller\\LikeController:likeComment' => '?',
            'App\\Controller\\LikeController:likePublication' => '?',
            'App\\Controller\\PublicationController:approve' => '?',
            'App\\Controller\\PublicationController:delete' => '?',
            'App\\Controller\\PublicationController:edit' => '?',
            'App\\Controller\\PublicationController:index' => '?',
            'App\\Controller\\PublicationController:like' => '?',
            'App\\Controller\\PublicationController:new' => '?',
            'App\\Controller\\PublicationController:reject' => '?',
            'App\\Controller\\PublicationController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
